/**
 * Build the Krakow street-name lexicon from the KAS "Alfabetyczny wykaz
 * ulic miasta Krakowa" PDF (zasieg_terytorialny). The output is a checked-in
 * TS module used by the address parser to normalize declined street forms
 * (e.g. "Karmelickiej" -> "Karmelicka").
 *
 * Usage: npm run tsx scripts/build-street-lexicon.ts [path-to-pdf]
 * With no path it downloads the PDF from the KAS site into $JCODE_SCRATCH_DIR.
 */
import { execFile } from "node:child_process";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { promisify } from "node:util";

import { streetKey } from "../src/crawler/street-key.ts";

const execFileAsync = promisify(execFile);

const PDF_URL =
	"https://www.malopolskie.kas.gov.pl/documents/3552230/4330444/zasieg_terytorialny";
const OUT_PATH = resolve("src/crawler/krakow-streets.ts");

const TYPE_RE =
	/^(ULICA|ALEJA|OSIEDLE|RONDO|PLAC|BULWAR|RYNEK|SKWER|PASAZ|PASAŻ|ZAULEK|ZAUŁEK|WYB|NAB|ESTAKADA|PLANTY|CZWOROBOK)\b/;

function titleCase(word: string): string {
	if (/^[IVXLCDM]+$/.test(word)) return word;
	return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
}

function canonicalName(upper: string): string {
	return upper
		.trim()
		.split(/\s+/)
		.map(titleCase)
		.join(" ");
}

async function extractPdfText(pdfPath: string): Promise<string> {
	const out = `${pdfPath}.txt`;
	await execFileAsync("pdftotext", ["-layout", pdfPath, out]);
	return readFile(out, "utf8");
}

async function main() {
	const pdfPath = process.argv[2];
	let pdf = pdfPath;
	if (!pdf) {
		const scratch = process.env.JCODE_SCRATCH_DIR ?? "/tmp";
		pdf = `${scratch}/krakow-streets.pdf`;
		console.log(`Downloading ${PDF_URL} -> ${pdf}`);
		const res = await fetch(PDF_URL);
		if (!res.ok) throw new Error(`download failed: ${res.status}`);
		await writeFile(pdf, Buffer.from(await res.arrayBuffer()));
	}

	console.log(`Extracting text from ${pdf}`);
	const text = await extractPdfText(pdf);

	const seen = new Map<string, string>();
	let scanned = 0;
	const ALL_CAPS = /^[A-ZĄĆĘŁŃÓŚŹŻ][A-ZĄĆĘŁŃÓŚŹŻ0-9'’-]*$/;
	for (const line of text.split("\n")) {
		if (!TYPE_RE.test(line)) continue;
		if (line.includes("Nazwa") && line.includes("Przydzia")) continue;
		scanned++;
		// The PDF uses proportional columns that drift between pages, so use
		// content instead of fixed offsets: the street name is the last
		// all-caps token (length >= 3) before the mixed-case Przydział and
		// Dzielnica columns. Trailing 2-letter Urząd codes (KR/NH/...) are
		// length 2 and skipped automatically. Multi-word names collapse to
		// their last word, which is fine for adjective-declension lookup.
		const tokens = line.split(/\s+/).filter(Boolean);
		let name: string | null = null;
		for (let i = tokens.length - 1; i >= 1; i--) {
			const t = tokens[i];
			if (ALL_CAPS.test(t) && /[A-ZĄĆĘŁŃÓŚŹŻ]/.test(t) && t.length >= 3) {
				name = t;
				break;
			}
		}
		if (!name) continue;
		seen.set(streetKey(name), canonicalName(name));
	}

	const names = [...seen.values()].sort((a, b) => a.localeCompare(b, "pl"));
	console.log(`scanned ${scanned} rows, kept ${names.length} unique street names`);

	const body = names.map((n) => JSON.stringify(n)).join(",\n\t");
	const module = `/**
 * Generated by scripts/build-street-lexicon.ts from the KAS
 * "Alfabetyczny wykaz ulic miasta Krakowa". Do not edit by hand.
 */
export const KRAKOW_STREETS: string[] = [
\t${body},
];
`;
	await mkdir(dirname(OUT_PATH), { recursive: true });
	await writeFile(OUT_PATH, module);
	console.log(`Wrote ${OUT_PATH} (${names.length} names)`);
}

main().catch((err) => {
	console.error(err);
	process.exitCode = 1;
});
