/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as MapRouteImport } from './routes/map'
import { Route as RentalsRouteImport } from './routes/rentals'
import { Route as ApiListingsRouteImport } from './routes/api/listings'
import { Route as ApiRentalAnalyticsRouteImport } from './routes/api/rental-analytics'
import { Route as ApiRentalGuestPricesRouteImport } from './routes/api/rental-guest-prices'
import { Route as ApiRentalStatsRouteImport } from './routes/api/rental-stats'
import { Route as ApiSourcesRouteImport } from './routes/api/sources'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiBuildingsGeojsonRouteImport } from './routes/api/buildings/geojson'
import { Route as ApiBuildingsHistoryIdsRouteImport } from './routes/api/buildings/history-ids'
import { Route as ApiBuildingsLabelsRouteImport } from './routes/api/buildings/labels'
import { Route as ApiBuildingsLookupRouteImport } from './routes/api/buildings/lookup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsRoute = RentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiListingsRoute = ApiListingsRouteImport.update({
  id: '/api/listings',
  path: '/api/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRentalAnalyticsRoute = ApiRentalAnalyticsRouteImport.update({
  id: '/api/rental-analytics',
  path: '/api/rental-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRentalGuestPricesRoute = ApiRentalGuestPricesRouteImport.update({
  id: '/api/rental-guest-prices',
  path: '/api/rental-guest-prices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRentalStatsRoute = ApiRentalStatsRouteImport.update({
  id: '/api/rental-stats',
  path: '/api/rental-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSourcesRoute = ApiSourcesRouteImport.update({
  id: '/api/sources',
  path: '/api/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildingsGeojsonRoute = ApiBuildingsGeojsonRouteImport.update({
  id: '/api/buildings/geojson',
  path: '/api/buildings/geojson',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildingsHistoryIdsRoute = ApiBuildingsHistoryIdsRouteImport.update({
  id: '/api/buildings/history-ids',
  path: '/api/buildings/history-ids',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildingsLabelsRoute = ApiBuildingsLabelsRouteImport.update({
  id: '/api/buildings/labels',
  path: '/api/buildings/labels',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildingsLookupRoute = ApiBuildingsLookupRouteImport.update({
  id: '/api/buildings/lookup',
  path: '/api/buildings/lookup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/listings': typeof ListingsRoute
  '/map': typeof MapRoute
  '/rentals': typeof RentalsRoute
  '/api/listings': typeof ApiListingsRoute
  '/api/rental-analytics': typeof ApiRentalAnalyticsRoute
  '/api/rental-guest-prices': typeof ApiRentalGuestPricesRoute
  '/api/rental-stats': typeof ApiRentalStatsRoute
  '/api/sources': typeof ApiSourcesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/buildings/geojson': typeof ApiBuildingsGeojsonRoute
  '/api/buildings/history-ids': typeof ApiBuildingsHistoryIdsRoute
  '/api/buildings/labels': typeof ApiBuildingsLabelsRoute
  '/api/buildings/lookup': typeof ApiBuildingsLookupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/listings': typeof ListingsRoute
  '/map': typeof MapRoute
  '/rentals': typeof RentalsRoute
  '/api/listings': typeof ApiListingsRoute
  '/api/rental-analytics': typeof ApiRentalAnalyticsRoute
  '/api/rental-guest-prices': typeof ApiRentalGuestPricesRoute
  '/api/rental-stats': typeof ApiRentalStatsRoute
  '/api/sources': typeof ApiSourcesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/buildings/geojson': typeof ApiBuildingsGeojsonRoute
  '/api/buildings/history-ids': typeof ApiBuildingsHistoryIdsRoute
  '/api/buildings/labels': typeof ApiBuildingsLabelsRoute
  '/api/buildings/lookup': typeof ApiBuildingsLookupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/listings': typeof ListingsRoute
  '/map': typeof MapRoute
  '/rentals': typeof RentalsRoute
  '/api/listings': typeof ApiListingsRoute
  '/api/rental-analytics': typeof ApiRentalAnalyticsRoute
  '/api/rental-guest-prices': typeof ApiRentalGuestPricesRoute
  '/api/rental-stats': typeof ApiRentalStatsRoute
  '/api/sources': typeof ApiSourcesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/buildings/geojson': typeof ApiBuildingsGeojsonRoute
  '/api/buildings/history-ids': typeof ApiBuildingsHistoryIdsRoute
  '/api/buildings/labels': typeof ApiBuildingsLabelsRoute
  '/api/buildings/lookup': typeof ApiBuildingsLookupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/listings'
    | '/map'
    | '/rentals'
    | '/api/listings'
    | '/api/rental-analytics'
    | '/api/rental-guest-prices'
    | '/api/rental-stats'
    | '/api/sources'
    | '/api/auth/$'
    | '/api/buildings/geojson'
    | '/api/buildings/history-ids'
    | '/api/buildings/labels'
    | '/api/buildings/lookup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/listings'
    | '/map'
    | '/rentals'
    | '/api/listings'
    | '/api/rental-analytics'
    | '/api/rental-guest-prices'
    | '/api/rental-stats'
    | '/api/sources'
    | '/api/auth/$'
    | '/api/buildings/geojson'
    | '/api/buildings/history-ids'
    | '/api/buildings/labels'
    | '/api/buildings/lookup'
  id:
    | '__root__'
    | '/'
    | '/listings'
    | '/map'
    | '/rentals'
    | '/api/listings'
    | '/api/rental-analytics'
    | '/api/rental-guest-prices'
    | '/api/rental-stats'
    | '/api/sources'
    | '/api/auth/$'
    | '/api/buildings/geojson'
    | '/api/buildings/history-ids'
    | '/api/buildings/labels'
    | '/api/buildings/lookup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ListingsRoute: typeof ListingsRoute
  MapRoute: typeof MapRoute
  RentalsRoute: typeof RentalsRoute
  ApiListingsRoute: typeof ApiListingsRoute
  ApiRentalAnalyticsRoute: typeof ApiRentalAnalyticsRoute
  ApiRentalGuestPricesRoute: typeof ApiRentalGuestPricesRoute
  ApiRentalStatsRoute: typeof ApiRentalStatsRoute
  ApiSourcesRoute: typeof ApiSourcesRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBuildingsGeojsonRoute: typeof ApiBuildingsGeojsonRoute
  ApiBuildingsHistoryIdsRoute: typeof ApiBuildingsHistoryIdsRoute
  ApiBuildingsLabelsRoute: typeof ApiBuildingsLabelsRoute
  ApiBuildingsLookupRoute: typeof ApiBuildingsLookupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals': {
      id: '/rentals'
      path: '/rentals'
      fullPath: '/rentals'
      preLoaderRoute: typeof RentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/listings': {
      id: '/api/listings'
      path: '/api/listings'
      fullPath: '/api/listings'
      preLoaderRoute: typeof ApiListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rental-analytics': {
      id: '/api/rental-analytics'
      path: '/api/rental-analytics'
      fullPath: '/api/rental-analytics'
      preLoaderRoute: typeof ApiRentalAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rental-guest-prices': {
      id: '/api/rental-guest-prices'
      path: '/api/rental-guest-prices'
      fullPath: '/api/rental-guest-prices'
      preLoaderRoute: typeof ApiRentalGuestPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rental-stats': {
      id: '/api/rental-stats'
      path: '/api/rental-stats'
      fullPath: '/api/rental-stats'
      preLoaderRoute: typeof ApiRentalStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sources': {
      id: '/api/sources'
      path: '/api/sources'
      fullPath: '/api/sources'
      preLoaderRoute: typeof ApiSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/buildings/geojson': {
      id: '/api/buildings/geojson'
      path: '/api/buildings/geojson'
      fullPath: '/api/buildings/geojson'
      preLoaderRoute: typeof ApiBuildingsGeojsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/buildings/history-ids': {
      id: '/api/buildings/history-ids'
      path: '/api/buildings/history-ids'
      fullPath: '/api/buildings/history-ids'
      preLoaderRoute: typeof ApiBuildingsHistoryIdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/buildings/labels': {
      id: '/api/buildings/labels'
      path: '/api/buildings/labels'
      fullPath: '/api/buildings/labels'
      preLoaderRoute: typeof ApiBuildingsLabelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/buildings/lookup': {
      id: '/api/buildings/lookup'
      path: '/api/buildings/lookup'
      fullPath: '/api/buildings/lookup'
      preLoaderRoute: typeof ApiBuildingsLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ListingsRoute: ListingsRoute,
  MapRoute: MapRoute,
  RentalsRoute: RentalsRoute,
  ApiListingsRoute: ApiListingsRoute,
  ApiRentalAnalyticsRoute: ApiRentalAnalyticsRoute,
  ApiRentalGuestPricesRoute: ApiRentalGuestPricesRoute,
  ApiRentalStatsRoute: ApiRentalStatsRoute,
  ApiSourcesRoute: ApiSourcesRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBuildingsGeojsonRoute: ApiBuildingsGeojsonRoute,
  ApiBuildingsHistoryIdsRoute: ApiBuildingsHistoryIdsRoute,
  ApiBuildingsLabelsRoute: ApiBuildingsLabelsRoute,
  ApiBuildingsLookupRoute: ApiBuildingsLookupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
